### ISSUE TITLE
Example does not work.

### ISSUE THREAD

**Issue by chrisShick** [M6Web/Firewall#17]
So, I decided to test the example yall provided by 

    $whiteList = array(
            '127.0.0.1',
            '198.168.0.*',
        );

        $blackList = array(
            '192.168.0.50',
        );

        $firewall = new Firewall();

        $connAllowed = $firewall
            ->setDefaultState(false)
            ->addList($whiteList, 'local', true)
            ->addList($blackList, 'localBad', false)
            ->setIpAddress('192.168.0.25')
            ->handle();

This does not work. Although, it clearly should allow 192.168.0.25 through.

**Comment by omansour** [comment]
ping @fabdsp @b-viguier WYT about that. It's a bug for me.

**Comment by fabdsp** [comment]
Not sure "198.168.0.*" doesn't contains "192.168.0.25" so the response is from the default state (false).
WYT ? @omansour @b-viguier @chrisShick

**Comment by omansour** [comment]
maybe we should correct the typo in the README - see https://github.com/M6Web/Firewall/pull/19

**Comment by chrisShick** [comment]
Wow I did not even see the typo.....
